---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cleanup
spec:
  description: This task will clean up a workspace by deleting all the files.
  workspaces:
    - name: output
  steps:
    - name: remove
      image: alpine:3
      workingDir: $(workspaces.output.path)
      script: |
        #!/usr/bin/env sh
        set -eu
        echo "Removing all files from $(workspaces.output.path) ..."
        if [ -d "$(workspaces.output.path)" ]; then
          rm -rf "$(workspaces.output.path)"/*
          rm -rf "$(workspaces.output.path)"/.[!.]*
          rm -rf "$(workspaces.output.path)"/..?*
        fi

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: lint
spec:
  description: This task installs dependencies and runs Flake8 linting.
  workspaces:
    - name: output
  steps:
    - name: flake8
      image: python:3.9-slim
      workingDir: $(workspaces.output.path)
      script: |
        #!/bin/bash
        set -e
        echo "DEBUG: Listing workspace files:"
        find $(workspaces.output.path) -print
        REQ_FILE=$(find $(workspaces.output.path) -type f -name "requirements.txt" | head -n 1)
        if [ -z "$REQ_FILE" ]; then
          echo "requirements.txt not found!"
          exit 1
        fi
        REPO_DIR=$(dirname "$REQ_FILE")
        echo "Found requirements.txt at $REQ_FILE"
        echo "Using repo directory: $REPO_DIR"
        python -m pip install --upgrade pip wheel
        pip install -r "$REQ_FILE"
        SERVICE_DIR=$(find $REPO_DIR -type d -name "service" | head -n 1)
        if [ -z "$SERVICE_DIR" ]; then
          echo "service folder not found!"
          exit 1
        fi
        echo "Running Flake8 on $SERVICE_DIR"
        flake8 "$SERVICE_DIR" --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 "$SERVICE_DIR" --count --max-complexity=10 --max-line-length=127 --statistics

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: nose
spec:
  description: This task installs dependencies and runs unit tests using Nose.
  workspaces:
    - name: output
  params:
    - name: args
      description: Arguments to pass to nose
      type: string
      default: "-v"
  steps:
    - name: nosetests
      image: python:3.9-slim
      workingDir: $(workspaces.output.path)
      script: |
        #!/bin/bash
        set -e
        echo "DEBUG: Listing workspace files:"
        find $(workspaces.output.path) -print
        REQ_FILE=$(find $(workspaces.output.path) -type f -name "requirements.txt" | head -n 1)
        if [ -z "$REQ_FILE" ]; then
          echo "requirements.txt not found!"
          exit 1
        fi
        REPO_DIR=$(dirname "$REQ_FILE")
        echo "Found requirements.txt at $REQ_FILE"
        echo "Using repo directory: $REPO_DIR"
        python -m pip install --upgrade pip wheel
        pip install -r "$REQ_FILE"
        nosetests $(params.args) "$REPO_DIR"
